improved testing framework + added more interpretation tests

diff --git a/src/test b/src/test
--- a/src/test
+++ b/src/test
@@ -2,7 +2,9 @@
 
 cs3110 compile test_interp.ml &&
     for file in tests/*.ml; do
-        echo "******* STARTING $file *******";
-        cs3110 run test_interp.ml $file &&
-        echo "******* ENDING $file *******";
+        if ! cs3110 run test_interp.ml $file ; then
+            echo "$file FAILED!";
+        else
+            echo "$file passed";
+        fi
     done
